scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("meal_plans/", include("meal_plans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TagDetailView,
    TagListView,
)


urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
]

tags/models.py
from django.db import models


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=20)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="tag")

tags/forms.py
from django import forms

try:
    from tags.models import Tag

    class TagForm(forms.ModelForm):
        class Meta:
            model = Tag
            fields = [
                "name",
            ]

except Exception:
    pass

tags/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from tags.models import Tag


# Create your views here.
def show_tags(request):
    context = {
        "tags": Tag.objects.all() if Tag else None,
    }
    return render(request, "tags/list.html", context)


class TagDeleteView(DeleteView):
    model = Tag
    template_name = "tags/delete.html"
    success_url = reverse_lazy("tags_list")


class TagUpdateView(UpdateView):
    model = Tag
    template_name = "tags/update.html"
    success_url = reverse_lazy("tags_list")


class TagCreateView(CreateView):
    model = Tag
    template_name = "tags/new.html"
    fields = ["name"]
    success_url = reverse_lazy("tags_list")


class TagDetailView(DetailView):
    model = Tag
    template_name = "tags/detail.html"
    success_url = reverse_lazy("tags_list")


class TagListView(ListView):
    model = Tag
    template_name = "tags/list.html"
    success_url = reverse_lazy("tags_list")

    def get_queryset(self):
        querystring = self.request.GET.get("q")
        if querystring is None:
            querystring = ""
        return Tag.objects.filter(name__icontains=querystring)

tags/templates/tags/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit {{ tag.name }} - Scrumptious</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Scrumptious</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li>
                    <a href="{% url 'tag_new' %}">Write a tag</a>
                </li>
            </ul>
        </nav>
    </header>
    <main class="tag-form">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ tag }}" permanently? </p>
            {{ form.as_p }}
            <div class="control">
                <button class="button">Delete tag</button>
            </div>
        </form>
    </main>
</body>

</html>

tags/templates/tags/detail.html
{% load static %}
{% load markdownify %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Tag - Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Scrumptious</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li>
                    <a href="{% url 'tag_new' %}">Write a tag</a>
                </li>
            </ul>
        </nav>
    </header>
    <p>
    <form method="GET">
        <input type="text" name="q">
        <button type="submit">Search</button>
    </form>
    </p>
    <main class="recipe-detail">
        <div>
            <a href="{% url 'tag_edit' tag.id %}">
                <botton>Edit tag</botton>
            </a>
            <a href="{% url 'tag_delete' tag.id %}">
                <botton>Delete tag</botton>
            </a>
            <div id="contentwrapper">
                <div id="right">
                <div id="imgdiv">
            {% if tag.image %}
            <img src="{{ tag.image }}">
            {% endif %}
        </div>
    </div>
    </div>
        <h1>{{ tag.name }}</h1>
        <p>
            Created on {{ tag.created }} |
            Updated on {{ tag.updated }}
        </p>
    </main>
</body>

</html>

tags/templates/tags/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit {{ tag.name }} - Scrumptious</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Scrumptious</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li>
                    <a href="{% url 'tag_new' %}">Write a tag</a>
                </li>
            </ul>
        </nav>
    </header>
    <main class="tag-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Update</button>
            </div>
        </form>
    </main>
</body>

</html>

tags/templates/tags/list.html
{% extends 'base.html' %}


{% block pagination %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock pagination %}


{% block content %}
<main class="recipe-grid">
  {% for tag in tag_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'tag_detail' tag.id %}">{{ tag.name }}</a>
    </h2>
    {% for recipe in tag.recipes.all %}
    <p>
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </p>
    {% endfor %}
  </div>
  {% empty %}
  <div>
    <h1>No tags, yet</h1>
    <p>
      Would you like to
      <a href="{% url 'tag_new' %}">create</a>
      one?
    </p>
  </div>
  {% endfor %}
</main>
{% endblock content %}

tags/templates/tags/new.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Tag - Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Scrumptious</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li>
                    <a href="{% url 'tag_new' %}">Write a tag</a>
                </li>
            </ul>
        </nav>
    </header>
    <main class="tag-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Create</button>
            </div>
        </form>
    </main>
</body>

</html>